[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules']
test = 'tests'
fs_permissions = [{ access = "read", path = "./" }]

[fmt]
tab_width = 2
line_length = 80

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
